print("Hello, world!")
print("Hee, hello there.")
print("Making quick progress.")
print("Funny")
print('Hey, does this still print?')
print("Ivo's computer does not work today.")
print('He said: "Hello."')

print(1)
print(1 + 1)
print(1 + 1 + 1)
print(3 + 2)
print(8)
print(5 + 8 + 8 - 8)
print("5 + 8 + 8 - 8")
